# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
      - dev
      - staging/*/*
      - release/*/*
    exclude:
      - user_story/*/*
      - feature/*/*
      - epic/*/*

pr:
  branches:
    include:
      - master
      - dev
      - staging/*/*
      - release/*/*
    exclude:
      - user_story/*/*
      - feature/*/*
      - epic/*/*

variables:
  solutionAngular: 'sources/TheSharpFactory.Web.Angular.sln'
  solutionReact: 'sources/TheSharpFactory.Web.Angular.React.sln'
  projectServices: 'sources/Services/Unified/Services.Unified.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:     
  - stage: 'nightly_builds'
    displayName: 'Dev Build'
    jobs: 
    - job: BuildAPIServices
      displayName: 'Build API Services'
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
        - task: UseDotNet@2
          displayName: 'NuGet Tool Installer'
          inputs:
            version: '3.1.301'
            includePreviewVersions: false # Required for preview versions
        - task: DotNetCoreCLI@2
          displayName: 'Build Services'
          inputs:
            command: 'build'
            projects: '$(projectServices)'
            arguments: '--configuration $(buildConfiguration)'
    - job: 'BuildAngularApp'
      displayName: 'Build Angular SPA'
      dependsOn: BuildAPIServices
      condition: succeeded('BuildAPIServices')
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - task: UseDotNet@2
        displayName: 'DonetNet Core Tool Installer'
        inputs:
          version: '3.1.301'
          includePreviewVersions: false # Required for preview versions
      - task: NodeTool@0
        displayName: 'Node.js Installer'
        inputs:
          versionSpec: '11.x' 
          checkLatest: true 
      - task: DotNetCoreCLI@2
        displayName: 'Build Angular Project'
        inputs:
          command: 'build'
          projects: '$(projectServices)'
          arguments: '--configuration $(buildConfiguration)'
    - job: 'BuildReactApp'
      displayName: 'Build React SPA'
      dependsOn: BuildAPIServices
      condition: succeeded('BuildAPIServices')
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
        - task: UseDotNet@2
          displayName: 'NuGet Tool Installer'
          inputs:
            version: '3.1.301'
            includePreviewVersions: false # Required for preview versions
        - task: NodeTool@0
          displayName: 'Node.js Installer'
          inputs:
            versionSpec: '11.x' 
            checkLatest: true 
        - task: DotNetCoreCLI@2
          displayName: 'Build Angular Project'
          inputs:
            command: 'build'
            projects: '$(projectServices)'
            arguments: '--configuration $(buildConfiguration)'